version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels: ["dependencies", "go"]
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      aws-sdk:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
      golang-x:
        patterns:
          - "golang.org/x/*"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels: ["dependencies", "github-actions"]
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"
